### ISSUE TITLE
Attendee email address required but not

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#294] opened 2017-04-14 21:35 UTC
The field is marked as required yet the descriptive text allows for you to leave it blank.

Field should not be required (if empty, email goes to logged in user's email address).

Descriptive text should be clearer:
_Enter the e-mail address of the recipient who will use this ticket. Leave blank to receive a redemption code for this registration that you can then forward on to whomever you like._

Also updated #213 with new text.

**Comment by aweingarten** [comment] 2017-04-17 20:41
Dup of https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/294

**Comment by alisonjo2786** [comment] 2017-04-19 19:11
Closed b/c dupe of #292

**Closed by alisonjo2786** 2017-04-19 19:11 UTC
