### ISSUE TITLE
Session user flags

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2017#396] opened 2017-05-08 04:03 UTC
ability for authorized user to select a session they plan to attend
this number displays on the screen for editors to monitor and move rooms as needed
a flagged session should show to users as an individualized schedule that they can monitor

**Comment by jdearie** [comment] 2017-05-08 21:48
duplicate of #365. incorporating any differences

**Closed by jdearie** 2017-05-08 21:48 UTC
Labels: enhancement
