### ISSUE TITLE
Revise User Flagged Session Block

### ISSUE THREAD

**Issue by brooke-heaton** [Drupal4Gov/Drupal-GovCon-2017#476] opened 2017-06-27 04:20 UTC
The block is currently showing on any users page - add contextual filter for the current user id. This has been done o Prod - need to export config.

**Comment by bheatonf1** [comment] 2017-07-14 02:22
Not sure if this is still an issue. Could not reproduce. Sorry that I didn't add more details - it was a late one :(

**Comment by bheatonf1** [comment] 2017-07-21 01:31
Yep this is still an issue noted by @jdearie I have resolved on Prod. This needs to be committed in code.

**Closed** 2017-10-16 14:56 UTC
